# Promise then && catch 的两种写法

## 问题

```js
// 第一种
promise.then(res=>{
  console.log('then:',res)
}).catch((err)=>{
  console.log('catch',err)
})
// 第二种
promise.then(res=>{
  console.log('then:',res)
},(err)=>{
  console.log('catch',err)
})
```

## 解析

- 第一种 catch 方法可以捕获到 catch 之前整条promise链路上所有抛出的异常

- 第二种 then 方法的第二个参数捕获的异常依赖于上一个promise 对象的执行结果

- promise.then(successCb,faildCb) 接收两个函数作为参数,来处理上一个 promise 对象的结果. then 方法返回的是 promise 对象.第一种链式写法,使用 catch ,相当于给前面一个 then 方法返回的 promise 注册回调,可以捕获到前面 then 没有被处理的异常.
第二种是回调函数写法,仅为上一个promise注册异常回调

- 如果是 promise 内部报错 reject 抛出错误后, then 的第二个参数就能捕获得到,如果 then 的第二个参数不存在,则 catch 方法会捕获到.

- 如果是 then 的第一个参数函数 resolve 中抛出了异常,即成功回调函数出现异常后,then 的第二个参数 reject 捕获不到, catch方法可以捕获到